---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: test-app
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: test-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: test-app
          image: grajamca/test-app:0.0.2
          ports:
            - name: http
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test-app
    tier: backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: http